export interface MasterProductItem {
  id: string;
  name: string;
  barcode: string;
  category: string;
  unit: string;
  suggestedCogs: number;
  suggestedSellingPrice: number;
  description?: string;
}

export const RETAIL_PRODUCT_MASTERLIST: MasterProductItem[] = [
  // 1. SEMBAKO & BUMBU DAPUR
  {
    id: 'mst-sembako-01',
    name: 'Beras Setra Ramos 5kg',
    barcode: '8991002100012',
    category: 'Sembako',
    unit: 'Sak',
    suggestedCogs: 65000,
    suggestedSellingPrice: 72000,
    description: 'Beras putih pulen kemasan 5kg',
  },
  {
    id: 'mst-sembako-02',
    name: 'Beras Pandan Wangi 5kg',
    barcode: '8991002100029',
    category: 'Sembako',
    unit: 'Sak',
    suggestedCogs: 72000,
    suggestedSellingPrice: 80000,
    description: 'Beras aromatik pandan wangi 5kg',
  },
  {
    id: 'mst-sembako-03',
    name: 'Minyak Goreng Bimoli Pouch 2L',
    barcode: '8992775112022',
    category: 'Sembako',
    unit: 'Pch',
    suggestedCogs: 33500,
    suggestedSellingPrice: 37000,
    description: 'Minyak kelapa sawit murni 2 Liter',
  },
  {
    id: 'mst-sembako-04',
    name: 'Minyak Goreng Filma Pouch 2L',
    barcode: '8992775222028',
    category: 'Sembako',
    unit: 'Pch',
    suggestedCogs: 34000,
    suggestedSellingPrice: 37500,
    description: 'Minyak goreng nabati 2 Liter',
  },
  {
    id: 'mst-sembako-05',
    name: 'Minyak Goreng SunCo Pouch 2L',
    barcode: '8992775442022',
    category: 'Sembako',
    unit: 'Pch',
    suggestedCogs: 34500,
    suggestedSellingPrice: 38000,
    description: 'Minyak goreng bening 2 Liter',
  },
  {
    id: 'mst-sembako-06',
    name: 'Minyak Goreng Tropical Botol 2L',
    barcode: '8992775332025',
    category: 'Sembako',
    unit: 'Btl',
    suggestedCogs: 35000,
    suggestedSellingPrice: 38500,
    description: 'Minyak goreng 2x penyaringan botol 2L',
  },
  {
    id: 'mst-sembako-07',
    name: 'Minyakita Bantal 1 Liter',
    barcode: '8992775001012',
    category: 'Sembako',
    unit: 'Btl',
    suggestedCogs: 14500,
    suggestedSellingPrice: 16000,
    description: 'Minyak goreng program pemerintah 1L',
  },
  {
    id: 'mst-sembako-08',
    name: 'Gula Pasir Gulaku Kuning 1kg',
    barcode: '8998866101019',
    category: 'Sembako',
    unit: 'Bks',
    suggestedCogs: 16000,
    suggestedSellingPrice: 18000,
    description: 'Gula tebu alami kemasan 1kg',
  },
  {
    id: 'mst-sembako-09',
    name: 'Gula Pasir Gulaku Putih Premium 1kg',
    barcode: '8998866101026',
    category: 'Sembako',
    unit: 'Bks',
    suggestedCogs: 16500,
    suggestedSellingPrice: 18500,
    description: 'Gula pasir kristal putih 1kg',
  },
  {
    id: 'mst-sembako-10',
    name: 'Telur Ayam Negeri 1kg',
    barcode: '8990001001015',
    category: 'Sembako',
    unit: 'Kg',
    suggestedCogs: 27000,
    suggestedSellingPrice: 30000,
    description: 'Telur ayam segar per kilogram',
  },
  {
    id: 'mst-sembako-11',
    name: 'Tepung Terigu Segitiga Biru 1kg',
    barcode: '8996001301014',
    category: 'Sembako',
    unit: 'Bks',
    suggestedCogs: 11000,
    suggestedSellingPrice: 13000,
    description: 'Tepung terigu serbaguna 1kg',
  },
  {
    id: 'mst-sembako-12',
    name: 'Garam Dapur Cap Kapal 250g',
    barcode: '8993001201012',
    category: 'Sembako',
    unit: 'Bks',
    suggestedCogs: 2500,
    suggestedSellingPrice: 3500,
    description: 'Garam beriodium halus 250g',
  },
  {
    id: 'mst-bumbu-01',
    name: 'Kecap Manis Bango Pouch 520ml',
    barcode: '8999999015201',
    category: 'Bumbu Dapur',
    unit: 'Pch',
    suggestedCogs: 21500,
    suggestedSellingPrice: 24500,
    description: 'Kecap kedelai hitam pilihan 520ml',
  },
  {
    id: 'mst-bumbu-02',
    name: 'Kecap Manis ABC Pouch 520ml',
    barcode: '8998888052012',
    category: 'Bumbu Dapur',
    unit: 'Pch',
    suggestedCogs: 19500,
    suggestedSellingPrice: 22500,
    description: 'Kecap manis kental ABC 520ml',
  },
  {
    id: 'mst-bumbu-03',
    name: 'Saus Sambal ABC Extra Pedas Botol 335ml',
    barcode: '8998888033516',
    category: 'Bumbu Dapur',
    unit: 'Btl',
    suggestedCogs: 14000,
    suggestedSellingPrice: 16500,
    description: 'Saus cabe extra pedas botol 335ml',
  },
  {
    id: 'mst-bumbu-04',
    name: 'Royco Kaldu Rasa Ayam 230g',
    barcode: '8999999023015',
    category: 'Bumbu Dapur',
    unit: 'Bks',
    suggestedCogs: 9500,
    suggestedSellingPrice: 11500,
    description: 'Penyedap rasa kaldu ayam pekat 230g',
  },
  {
    id: 'mst-bumbu-05',
    name: 'Masako Kaldu Rasa Sapi 100g',
    barcode: '8992770100115',
    category: 'Bumbu Dapur',
    unit: 'Bks',
    suggestedCogs: 4500,
    suggestedSellingPrice: 5500,
    description: 'Bumbu kaldu ekstrak daging sapi 100g',
  },
  {
    id: 'mst-bumbu-06',
    name: 'Ajinomoto MSG 100g',
    barcode: '8992770100221',
    category: 'Bumbu Dapur',
    unit: 'Bks',
    suggestedCogs: 4000,
    suggestedSellingPrice: 5000,
    description: 'Penguat rasa monosodium glutamat 100g',
  },

  // 2. MIE INSTAN & MAKANAN CEPAT SAJI
  {
    id: 'mst-mie-01',
    name: 'Indomie Goreng Spesial 85g',
    barcode: '089686010014',
    category: 'Makanan & Mie',
    unit: 'Bks',
    suggestedCogs: 2850,
    suggestedSellingPrice: 3500,
    description: 'Mie goreng instan rasa original 85g',
  },
  {
    id: 'mst-mie-02',
    name: 'Indomie Kuah Ayam Bawang 69g',
    barcode: '089686010021',
    category: 'Makanan & Mie',
    unit: 'Bks',
    suggestedCogs: 2800,
    suggestedSellingPrice: 3500,
    description: 'Mie kuah kaldu ayam bawang gurih',
  },
  {
    id: 'mst-mie-03',
    name: 'Indomie Kuah Soto Mie 70g',
    barcode: '089686010038',
    category: 'Makanan & Mie',
    unit: 'Bks',
    suggestedCogs: 2800,
    suggestedSellingPrice: 3500,
    description: 'Mie instan kuah soto khas Indonesia',
  },
  {
    id: 'mst-mie-04',
    name: 'Indomie Kuah Kari Ayam 72g',
    barcode: '089686010045',
    category: 'Makanan & Mie',
    unit: 'Bks',
    suggestedCogs: 2900,
    suggestedSellingPrice: 3500,
    description: 'Mie kuah kari kental beraroma',
  },
  {
    id: 'mst-mie-05',
    name: 'Indomie Goreng Rendang 91g',
    barcode: '089686010052',
    category: 'Makanan & Mie',
    unit: 'Bks',
    suggestedCogs: 2950,
    suggestedSellingPrice: 3500,
    description: 'Mie goreng cita rasa rendang Padang',
  },
  {
    id: 'mst-mie-06',
    name: 'Indomie Hype Abis Ayam Geprek 85g',
    barcode: '089686010069',
    category: 'Makanan & Mie',
    unit: 'Bks',
    suggestedCogs: 2950,
    suggestedSellingPrice: 3500,
    description: 'Mie goreng pedas sensasi cabai geprek',
  },
  {
    id: 'mst-mie-07',
    name: 'Mie Sedaap Goreng 90g',
    barcode: '8998866200118',
    category: 'Makanan & Mie',
    unit: 'Bks',
    suggestedCogs: 2800,
    suggestedSellingPrice: 3500,
    description: 'Mie goreng dengan taburan bawang kriuk',
  },
  {
    id: 'mst-mie-08',
    name: 'Mie Sedaap Soto Madura 75g',
    barcode: '8998866200217',
    category: 'Makanan & Mie',
    unit: 'Bks',
    suggestedCogs: 2750,
    suggestedSellingPrice: 3500,
    description: 'Mie kuah soto dengan koya gurih',
  },
  {
    id: 'mst-mie-09',
    name: 'Pop Mie Rasa Ayam Bawang 75g',
    barcode: '089686020013',
    category: 'Makanan & Mie',
    unit: 'Cup',
    suggestedCogs: 4800,
    suggestedSellingPrice: 6000,
    description: 'Mie instan cup praktis rasa ayam bawang',
  },
  {
    id: 'mst-mie-10',
    name: 'Pop Mie Rasa Baso Sapi 75g',
    barcode: '089686020020',
    category: 'Makanan & Mie',
    unit: 'Cup',
    suggestedCogs: 4800,
    suggestedSellingPrice: 6000,
    description: 'Mie instan cup kuah baso sapi',
  },
  {
    id: 'mst-mie-11',
    name: 'Pop Mie Pedes Gledek 75g',
    barcode: '089686020037',
    category: 'Makanan & Mie',
    unit: 'Cup',
    suggestedCogs: 5000,
    suggestedSellingPrice: 6500,
    description: 'Mie goreng cup super pedas gledek',
  },
  {
    id: 'mst-mie-12',
    name: 'Sarimi Isi 2 Ayam Kecap 120g',
    barcode: '089686030012',
    category: 'Makanan & Mie',
    unit: 'Bks',
    suggestedCogs: 3800,
    suggestedSellingPrice: 4500,
    description: 'Porsi ganda 2 keping mie rasa ayam kecap',
  },

  // 3. MINUMAN KEMASAN & AIR MINERAL
  {
    id: 'mst-minum-01',
    name: 'Aqua Air Mineral Botol 600ml',
    barcode: '8992752011117',
    category: 'Minuman',
    unit: 'Btl',
    suggestedCogs: 2900,
    suggestedSellingPrice: 4000,
    description: 'Air mineral pegunungan botol sedang 600ml',
  },
  {
    id: 'mst-minum-02',
    name: 'Aqua Air Mineral Botol 1500ml',
    barcode: '8992752011216',
    category: 'Minuman',
    unit: 'Btl',
    suggestedCogs: 5200,
    suggestedSellingPrice: 7000,
    description: 'Air mineral kemasan besar 1.5 Liter',
  },
  {
    id: 'mst-minum-03',
    name: 'Le Minerale Botol 600ml',
    barcode: '8996001600148',
    category: 'Minuman',
    unit: 'Btl',
    suggestedCogs: 2800,
    suggestedSellingPrice: 3500,
    description: 'Air mineral dengan mineral alami 600ml',
  },
  {
    id: 'mst-minum-04',
    name: 'Le Minerale Botol 1500ml',
    barcode: '8996001600247',
    category: 'Minuman',
    unit: 'Btl',
    suggestedCogs: 5000,
    suggestedSellingPrice: 6500,
    description: 'Air mineral galon mini / botol besar 1500ml',
  },
  {
    id: 'mst-minum-05',
    name: 'Teh Botol Sosro Kotak 250ml',
    barcode: '8992696404106',
    category: 'Minuman',
    unit: 'Kotak',
    suggestedCogs: 2800,
    suggestedSellingPrice: 4000,
    description: 'Teh melati wangi kemasan tetra pak 250ml',
  },
  {
    id: 'mst-minum-06',
    name: 'Teh Pucuk Harum Botol 350ml',
    barcode: '8996001414011',
    category: 'Minuman',
    unit: 'Btl',
    suggestedCogs: 2900,
    suggestedSellingPrice: 4000,
    description: 'Teh melati pucuk daun pilihan 350ml',
  },
  {
    id: 'mst-minum-07',
    name: 'Teh Javana Gula Batu 350ml',
    barcode: '8998866500119',
    category: 'Minuman',
    unit: 'Btl',
    suggestedCogs: 2700,
    suggestedSellingPrice: 3500,
    description: 'Minuman teh rasa gula batu 350ml',
  },
  {
    id: 'mst-minum-08',
    name: 'Floridina Orange Pulpy 350ml',
    barcode: '8998866400112',
    category: 'Minuman',
    unit: 'Btl',
    suggestedCogs: 2800,
    suggestedSellingPrice: 3500,
    description: 'Jus jeruk dengan bulir jeruk asli Florida',
  },
  {
    id: 'mst-minum-09',
    name: 'Pocari Sweat Botol 500ml',
    barcode: '8999908101018',
    category: 'Minuman',
    unit: 'Btl',
    suggestedCogs: 6500,
    suggestedSellingPrice: 8000,
    description: 'Minuman isotonik pengganti ion tubuh 500ml',
  },
  {
    id: 'mst-minum-10',
    name: 'Coca-Cola Botol PET 390ml',
    barcode: '8992761111112',
    category: 'Minuman',
    unit: 'Btl',
    suggestedCogs: 4500,
    suggestedSellingPrice: 6000,
    description: 'Minuman berkarbonasi rasa cola 390ml',
  },
  {
    id: 'mst-minum-11',
    name: 'Fanta Strawberry Botol 390ml',
    barcode: '8992761222221',
    category: 'Minuman',
    unit: 'Btl',
    suggestedCogs: 4500,
    suggestedSellingPrice: 6000,
    description: 'Minuman soda rasa stroberi segar 390ml',
  },
  {
    id: 'mst-minum-12',
    name: 'Sprite Botol PET 390ml',
    barcode: '8992761333330',
    category: 'Minuman',
    unit: 'Btl',
    suggestedCogs: 4500,
    suggestedSellingPrice: 6000,
    description: 'Minuman soda jernih rasa lemon-lime 390ml',
  },

  // 4. SUSU & KOPI
  {
    id: 'mst-susu-01',
    name: 'Ultra Milk Full Cream UHT 250ml',
    barcode: '8992741981017',
    category: 'Susu & Olahan',
    unit: 'Kotak',
    suggestedCogs: 5800,
    suggestedSellingPrice: 7500,
    description: 'Susu sapi segar full cream UHT 250ml',
  },
  {
    id: 'mst-susu-02',
    name: 'Ultra Milk Cokelat UHT 250ml',
    barcode: '8992741981024',
    category: 'Susu & Olahan',
    unit: 'Kotak',
    suggestedCogs: 5800,
    suggestedSellingPrice: 7500,
    description: 'Susu cair rasa cokelat lezat 250ml',
  },
  {
    id: 'mst-susu-03',
    name: 'Bear Brand Susu Steril 189ml',
    barcode: '7613032501018',
    category: 'Susu & Olahan',
    unit: 'Kaleng',
    suggestedCogs: 9500,
    suggestedSellingPrice: 11500,
    description: 'Susu steril murni tanpa bahan pengawet 189ml',
  },
  {
    id: 'mst-kopi-01',
    name: 'Kopi Kapal Api Spesial Mix 10x24g',
    barcode: '8991001100112',
    category: 'Kopi & Teh',
    unit: 'Renceng',
    suggestedCogs: 12500,
    suggestedSellingPrice: 15000,
    description: 'Kopi bubuk hitam + gula 1 renceng (10 sachet)',
  },
  {
    id: 'mst-kopi-02',
    name: 'Luwak White Koffie 10x20g',
    barcode: '8991001200119',
    category: 'Kopi & Teh',
    unit: 'Renceng',
    suggestedCogs: 13000,
    suggestedSellingPrice: 15500,
    description: 'Kopi putih ramah lambung 10 sachet',
  },
  {
    id: 'mst-kopi-03',
    name: 'Good Day Mocacinno 10x20g',
    barcode: '8991001300116',
    category: 'Kopi & Teh',
    unit: 'Renceng',
    suggestedCogs: 12000,
    suggestedSellingPrice: 14500,
    description: 'Kopi instan 3-in-1 rasa moka 10 sachet',
  },
  {
    id: 'mst-kopi-04',
    name: 'Torabika Duo Kopi Gula 10x25g',
    barcode: '8996001400113',
    category: 'Kopi & Teh',
    unit: 'Renceng',
    suggestedCogs: 11500,
    suggestedSellingPrice: 14000,
    description: 'Kopi robusta mantap dan gula pasir 10 sachet',
  },

  // 5. SNACK & BISKUIT
  {
    id: 'mst-snack-01',
    name: 'Chitato Sapi Panggang 68g',
    barcode: '089686410012',
    category: 'Makanan Ringan',
    unit: 'Bks',
    suggestedCogs: 9500,
    suggestedSellingPrice: 12000,
    description: 'Keripik kentang bergelombang rasa beef BBQ',
  },
  {
    id: 'mst-snack-02',
    name: 'Chiki Twist Jagung Bakar 40g',
    barcode: '089686420019',
    category: 'Makanan Ringan',
    unit: 'Bks',
    suggestedCogs: 2500,
    suggestedSellingPrice: 3500,
    description: 'Camilan jagung renyah bentuk pilin 40g',
  },
  {
    id: 'mst-snack-03',
    name: 'Taro Net Rumput Laut 36g',
    barcode: '8992770200112',
    category: 'Makanan Ringan',
    unit: 'Bks',
    suggestedCogs: 3800,
    suggestedSellingPrice: 5000,
    description: 'Camilan kentang jaring rasa seaweed 36g',
  },
  {
    id: 'mst-snack-04',
    name: 'Kusuka Keripik Singkong Original 60g',
    barcode: '8992770300119',
    category: 'Makanan Ringan',
    unit: 'Bks',
    suggestedCogs: 4800,
    suggestedSellingPrice: 6500,
    description: 'Keripik singkong gurih iris tipis 60g',
  },
  {
    id: 'mst-snack-05',
    name: 'Roma Kelapa Biskuit 300g',
    barcode: '8996001500110',
    category: 'Biskuit & Kue',
    unit: 'Bks',
    suggestedCogs: 9800,
    suggestedSellingPrice: 12000,
    description: 'Biskuit renyah kelapa gurih 300g',
  },
  {
    id: 'mst-snack-06',
    name: 'Roma Malkist Abon Sapi 135g',
    barcode: '8996001500219',
    category: 'Biskuit & Kue',
    unit: 'Bks',
    suggestedCogs: 6500,
    suggestedSellingPrice: 8000,
    description: 'Biskuit malkist dengan taburan abon sapi asli',
  },
  {
    id: 'mst-snack-07',
    name: 'Oreo Vanilla Biskuit Roll 133g',
    barcode: '7622210100115',
    category: 'Biskuit & Kue',
    unit: 'Bks',
    suggestedCogs: 8000,
    suggestedSellingPrice: 10000,
    description: 'Biskuit cokelat dengan krim vanila 133g',
  },
  {
    id: 'mst-snack-08',
    name: 'Nabati Wafer Richeese Keju 145g',
    barcode: '8993175100115',
    category: 'Biskuit & Kue',
    unit: 'Bks',
    suggestedCogs: 6800,
    suggestedSellingPrice: 8500,
    description: 'Wafer renyah isi krim keju berenergi',
  },
  {
    id: 'mst-snack-09',
    name: 'SilverQueen Cashew Cokelat 58g',
    barcode: '8991001500110',
    category: 'Makanan Ringan',
    unit: 'Pcs',
    suggestedCogs: 13500,
    suggestedSellingPrice: 16500,
    description: 'Cokelat batang isi kacang mete 58g',
  },

  // 6. KEBUTUHAN RUMAH TANGGA & TOILETRIES
  {
    id: 'mst-rt-01',
    name: 'Sunlight Jeruk Nipis Pencuci Piring 700ml',
    barcode: '8999999070019',
    category: 'Kebutuhan Rumah',
    unit: 'Pch',
    suggestedCogs: 13000,
    suggestedSellingPrice: 15500,
    description: 'Sabun cuci piring anti lemak ekstrak jeruk nipis',
  },
  {
    id: 'mst-rt-02',
    name: 'Mama Lemon Jeruk Nipis 680ml',
    barcode: '8998866700113',
    category: 'Kebutuhan Rumah',
    unit: 'Pch',
    suggestedCogs: 11000,
    suggestedSellingPrice: 13500,
    description: 'Cairan pembersih piring dan buah jeruk nipis',
  },
  {
    id: 'mst-rt-03',
    name: 'Rinso Molto Deterjen Bubuk 770g',
    barcode: '8999999077018',
    category: 'Kebutuhan Rumah',
    unit: 'Bks',
    suggestedCogs: 18500,
    suggestedSellingPrice: 22000,
    description: 'Deterjen bubuk pembersih noda konsentrat tinggi',
  },
  {
    id: 'mst-rt-04',
    name: 'Daia Deterjen Bubuk Bunga 850g',
    barcode: '8998866800110',
    category: 'Kebutuhan Rumah',
    unit: 'Bks',
    suggestedCogs: 16000,
    suggestedSellingPrice: 19000,
    description: 'Deterjen wangi bunga lembut di tangan 850g',
  },
  {
    id: 'mst-rt-05',
    name: 'Downy Pewangi Sunrise Fresh 650ml',
    barcode: '4902430100115',
    category: 'Kebutuhan Rumah',
    unit: 'Pch',
    suggestedCogs: 23000,
    suggestedSellingPrice: 27000,
    description: 'Konsentrat pewangi dan pelembut pakaian',
  },
  {
    id: 'mst-rt-06',
    name: 'So Klin Pembersih Lantai Lavender 780ml',
    barcode: '8998866900117',
    category: 'Kebutuhan Rumah',
    unit: 'Pch',
    suggestedCogs: 9500,
    suggestedSellingPrice: 12000,
    description: 'Pembersih lantai wangi lavender higienis',
  },
  {
    id: 'mst-rt-07',
    name: 'Wipol Karbol Wangi Cemara 750ml',
    barcode: '8999999075014',
    category: 'Kebutuhan Rumah',
    unit: 'Pch',
    suggestedCogs: 16000,
    suggestedSellingPrice: 19000,
    description: 'Cairan disinfektan pembunuh kuman wangi pinus',
  },
  {
    id: 'mst-rt-08',
    name: 'Baygon Aerosol Lavender 600ml',
    barcode: '8992770400116',
    category: 'Kebutuhan Rumah',
    unit: 'Kaleng',
    suggestedCogs: 36000,
    suggestedSellingPrice: 42000,
    description: 'Semprotan anti nyamuk dan kecoa cepat',
  },
  {
    id: 'mst-toiletries-01',
    name: 'Sabun Mandi Batang Lifebuoy Total 10 110g',
    barcode: '8999999011012',
    category: 'Perawatan Tubuh',
    unit: 'Pcs',
    suggestedCogs: 4000,
    suggestedSellingPrice: 5000,
    description: 'Sabun antibakteri perlindungan keluarga 110g',
  },
  {
    id: 'mst-toiletries-02',
    name: 'Sabun Mandi Dettol Original 100g',
    barcode: '8991001600117',
    category: 'Perawatan Tubuh',
    unit: 'Pcs',
    suggestedCogs: 6000,
    suggestedSellingPrice: 7500,
    description: 'Sabun batang antiseptik original 100g',
  },
  {
    id: 'mst-toiletries-03',
    name: 'Sampo Pantene Anti Dandruff 160ml',
    barcode: '4902430200112',
    category: 'Perawatan Tubuh',
    unit: 'Btl',
    suggestedCogs: 24000,
    suggestedSellingPrice: 28500,
    description: 'Sampo perawatan kulit kepala bebas ketombe',
  },
  {
    id: 'mst-toiletries-04',
    name: 'Sampo Clear Men Cool Sport Menthol 160ml',
    barcode: '8999999016017',
    category: 'Perawatan Tubuh',
    unit: 'Btl',
    suggestedCogs: 25000,
    suggestedSellingPrice: 29500,
    description: 'Sampo anti ketombe sensasi dingin menthol',
  },
  {
    id: 'mst-toiletries-05',
    name: 'Pasta Gigi Pepsodent White 190g',
    barcode: '8999999019018',
    category: 'Perawatan Tubuh',
    unit: 'Tub',
    suggestedCogs: 12500,
    suggestedSellingPrice: 15000,
    description: 'Pasta gigi pencegah gigi berlubang 190g',
  },
  {
    id: 'mst-toiletries-06',
    name: 'Pasta Gigi Ciptadent Maxi Complete 190g',
    barcode: '8998866300115',
    category: 'Perawatan Tubuh',
    unit: 'Tub',
    suggestedCogs: 8500,
    suggestedSellingPrice: 10500,
    description: 'Pasta gigi kalsium mikro aktif 190g',
  },

  // 7. KESEHATAN & OBAT BEBAS
  {
    id: 'mst-obat-01',
    name: 'Tolak Angin Cair Sidomuncul 15ml',
    barcode: '8998866400228',
    category: 'Obat & Kesehatan',
    unit: 'Sachet',
    suggestedCogs: 3600,
    suggestedSellingPrice: 4500,
    description: 'Obat herbal masuk angin dan daya tahan tubuh',
  },
  {
    id: 'mst-obat-02',
    name: 'Paramex Tablet Sakit Kepala',
    barcode: '8992770500113',
    category: 'Obat & Kesehatan',
    unit: 'Strip',
    suggestedCogs: 2500,
    suggestedSellingPrice: 3500,
    description: 'Obat pereda sakit kepala dan sakit gigi',
  },
  {
    id: 'mst-obat-03',
    name: 'Bodrex Tablet Sakit Kepala',
    barcode: '8992770600110',
    category: 'Obat & Kesehatan',
    unit: 'Strip',
    suggestedCogs: 2500,
    suggestedSellingPrice: 3500,
    description: 'Pereda nyeri dan penurun demam cepat',
  },
  {
    id: 'mst-obat-04',
    name: 'Promag Tablet Sakit Maag',
    barcode: '8992770700117',
    category: 'Obat & Kesehatan',
    unit: 'Strip',
    suggestedCogs: 7500,
    suggestedSellingPrice: 9500,
    description: 'Tablet kunyah pereda asam lambung & kembung',
  },
  {
    id: 'mst-obat-05',
    name: 'Minyak Kayu Putih Cap Lang 60ml',
    barcode: '8992770800114',
    category: 'Obat & Kesehatan',
    unit: 'Btl',
    suggestedCogs: 21000,
    suggestedSellingPrice: 25000,
    description: 'Minyak kayu putih murni hangat berkhasiat',
  },
  {
    id: 'mst-obat-06',
    name: 'Hansaplast Plester Kain Elastis 10s',
    barcode: '8992770900111',
    category: 'Obat & Kesehatan',
    unit: 'Bks',
    suggestedCogs: 4500,
    suggestedSellingPrice: 6000,
    description: 'Plester luka elastis tahan air isi 10',
  },

  // 8. ROKOK & TEMBAKAU
  {
    id: 'mst-rokok-01',
    name: 'Sampoerna A Mild 16',
    barcode: '8992771000117',
    category: 'Rokok',
    unit: 'Bks',
    suggestedCogs: 33500,
    suggestedSellingPrice: 36000,
    description: 'Rokok kretek filter mild isi 16 batang',
  },
  {
    id: 'mst-rokok-02',
    name: 'Djarum Super 12',
    barcode: '8992771100114',
    category: 'Rokok',
    unit: 'Bks',
    suggestedCogs: 22500,
    suggestedSellingPrice: 24500,
    description: 'Rokok kretek filter khas Djarum isi 12',
  },
  {
    id: 'mst-rokok-03',
    name: 'Gudang Garam Surya 16',
    barcode: '8992771200111',
    category: 'Rokok',
    unit: 'Bks',
    suggestedCogs: 32000,
    suggestedSellingPrice: 34500,
    description: 'Rokok kretek filter aroma mantap isi 16',
  },
  {
    id: 'mst-rokok-04',
    name: 'Marlboro Merah 20',
    barcode: '8992771300118',
    category: 'Rokok',
    unit: 'Bks',
    suggestedCogs: 42000,
    suggestedSellingPrice: 45000,
    description: 'Rokok putih filter internasional isi 20',
  },
];

/**
 * Helper to search masterlist by keyword (name, category, or barcode)
 */
export function searchProductMasterlist(
  query: string,
  limit: number = 8
): MasterProductItem[] {
  const clean = query.trim().toLowerCase();
  if (!clean) return [];

  const matched = RETAIL_PRODUCT_MASTERLIST.filter((item) => {
    return (
      item.name.toLowerCase().includes(clean) ||
      item.barcode.toLowerCase().includes(clean) ||
      item.category.toLowerCase().includes(clean)
    );
  });

  return matched.slice(0, limit);
}

/**
 * Helper to find masterlist product by exact barcode match
 */
export function findMasterProductByBarcode(
  barcode: string
): MasterProductItem | undefined {
  const clean = barcode.trim();
  if (!clean) return undefined;
  return RETAIL_PRODUCT_MASTERLIST.find((item) => item.barcode === clean);
}
